name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: upstream-owner
          base: main
          head: main
